version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
shallow_clone: true
build_script:
- ps: Get-ChildItem -Path . -Recurse -Filter "cron.ps1" | ForEach-Object { . $_.FullName }
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
